############ options ####################


############ Rule Extraction ############

file_source_tree : /poisson2/home2/raphael/ntcir10/data.full/data.en.tree
file_source_dep : /poisson2/home2/raphael/ntcir10/data.full/data.en.dep
# taget side with plain text
file_target : /poisson2/home2/raphael/ntcir10/data.full/data.ja
# aligment file
file_alignment : /poisson2/home2/raphael/ntcir10/data.full/aligned.grow-diag-final-and

# lexical probability table
file_lex_e2f : /poisson2/home2/raphael/ntcir10/data.full/lex.e2f
file_lex_f2e : /poisson2/home2/raphael/ntcir10/data.full/lex.f2e

# output file of rules extracted
rule_table_path : /poisson2/home2/raphael/ntcir10/gentile.full.model

# language model setting

file_lm : /poisson2/home2/raphael/ntcir10/lm/ja.full.binary
max_gram : 5

x_as_tag : no

max_merge_nodes : 3
max_tokens : 6
min_deep_extract_terminals : 3
max_transaction_rate : 3

############ Probability Estimate ############

# input file of rules_extracted

dispersion_tables : 10
max_rules_for_each_source: 2000

############ Decoder ############

debug : no

#input file of rule table is same as file_rules_final

#input translation data
file_translation_input_tree : /poisson2/home2/raphael/ntcir10/intrinsic/data.en.tree
file_translation_input_dep : /poisson2/home2/raphael/ntcir10/intrinsic/data.en.dep
# output translation data
file_translation_output : /poisson2/home2/raphael/ntcir10/intrinsic/gentile.full.glue.ja

# the number of nbest in the mode of nbest output , make sure it bigger than 0;
nbest : 50

size_cube_pruning : 2000

size_beam : 2000

# max non-terminals in tree reconstruction
reconstruction_max_nt : 2

use_glue_ruletable : yes

enable_chiropractic : no

# weight settings
weights :
#- 0.00596950305498102
#- 0.0702448396785429
#- 0.0544369594255997
#- 0.135654037244263
#- 0.157281527993101
#- -0.0436228192716449
#- -0.144734369757711
#- -0.024341215018477
#- 0.363714728555679
- 0.00841060834942518
- -0.0184563079131765
- 0.224245325242622
- 0.0180903061242853
- 0.0445795701146025
- 0.021116948256982
- -0.0108937404294877
- 0.360779329946953
- 0.293427863622466
